export const ERROR_CODES = {
  AUTH: {
    MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
    INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    INVALID_RESET_PASSWORD_TOKEN: 'AUTH_INVALID_RESET_PASSWORD_TOKEN'
  },
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  },
  ORGANIZATION: {
    NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
    ALREADY_EXISTS: 'ORGANIZATION_ALREADY_EXISTS',
    MISSING_ID: 'ORGANIZATION_MISSING_ID'
  },
  ORGANIZATION_MEMBER: {
    NOT_FOUND: 'ORGANIZATION_MEMBER_NOT_FOUND',
    ALREADY_EXISTS: 'ORGANIZATION_MEMBER_ALREADY_EXISTS',
    MISSING_ID: 'ORGANIZATION_MEMBER_MISSING_ID',
    LAST_OWNER_CANNOT_BE_REMOVED: "ORGANIZATION_MEMBER_LAST_OWNER_CANNOT_BE_REMOVED",
    FORBIDDEN: "ORGANIZATION_MEMBER_FORBIDDEN",
  },
  PROJECT: {
    NOT_FOUND: 'PROJECT_NOT_FOUND',
    ALREADY_EXISTS: 'PROJECT_ALREADY_EXISTS',
    MISSING_ID: 'PROJECT_MISSING_ID'
  },
  PROJECT_MEMBER: {
    NOT_FOUND: 'PROJECT_MEMBER_NOT_FOUND',
    ALREADY_EXISTS: 'PROJECT_MEMBER_ALREADY_EXISTS',
    MISSING_ID: 'PROJECT_MEMBER_MISSING_ID'
  },
  TASK: {
    NOT_FOUND: 'TASK_NOT_FOUND',
    ALREADY_EXISTS: 'TASK_ALREADY_EXISTS',
    MISSING_ID: 'TASK_MISSING_ID'
  },
  COMMON: {
    VALIDATION_ERROR: 'COMMON_VALIDATION_ERROR',
    INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
    FORBIDDEN: 'COMMON_FORBIDDEN',
  },
} as const;

type ErrorCodesMap = typeof ERROR_CODES;
export type ErrorCode = {
  [K in keyof typeof ERROR_CODES]: (typeof ERROR_CODES)[K][keyof (typeof ERROR_CODES)[K]]
}[keyof typeof ERROR_CODES];

export type ErrorMessages = {
  [K in keyof ErrorCodesMap]: {
    [C in keyof ErrorCodesMap[K]]: string
  }
}