FROM node:24-alpine

# python3/make/g++ нужны для нативной компиляции bcrypt при npm install
RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3000


CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npx tsx watch src/index.ts"]
