export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  COMMON_VALIDATION_ERROR: 'COMMON_VALIDATION_ERROR',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  DEFAULT: 'DEFAULT',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];